name: List Files in Repository

on: [push]

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List all files
        run: |
          echo "Listing all files in the repository:"
          ls -R

      - name: Clone another GitHub repository
        env:
          GH_PAT: ${{ secrets.test_github }}
        run: |
          echo "Cloning another GitHub repository"
          git clone https://username:${GH_PAT}@github.com/mohantest14242/python-testing.git
      - name: listing the all the cloned files 
        run: 
          ls
